### ISSUE TITLE
目标主机不可达

### ISSUE THREAD

**Issue by newhwa** [chenjiandongx/async-proxy-pool#1]
本机访问没任何问题，但是外部（虚拟机外部）访问不了。
其他应用没问题，所以应该不是网络问题。

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/45790404-41932700-bcb7-11e8-9d9a-20acfbb8a372.png)

朋友你是想干嘛

**Comment by newhwa** [comment]
> ![image](https://user-images.githubusercontent.com/19553554/45790404-41932700-bcb7-11e8-9d9a-20acfbb8a372.png)
> 
> 朋友你是想干嘛

不好意思, 本想删除重新详细描述,没找到删除的按键

**Comment by chenjiandongx** [comment]
所有网站都访问不了？

**Comment by 2Kil** [comment]
修改config.py中的SANIC_HOST = "局域网IP"
