### ISSUE TITLE
ok 改好了

### ISSUE THREAD

**Issue by nekolr** [chenjiandongx/async-proxy-pool#11]
ok 改好了

_Originally posted by @chenjiandongx in https://github.com/chenjiandongx/async-proxy-pool/issues/2#issuecomment-440532911_

您好，我再次遇到了这个问题，然后手动修改了 requirements 文件中 redis 的版本号，重新安装了一遍 redis 库才好，请修复之

**Comment by chenjiandongx** [comment]
你是用的是哪个版本的 redis？

**Comment by nekolr** [comment]
你的 requirements 中的 redis 没有指定版本，默认安装的是最新的，当前是 3.2.0。后来我修改了 requirements 文件中 redis 的版本，指定为 2.10.6，重新安装就可以了

**Comment by nekolr** [comment]
我看到您之前修复过这个问题，只不过后来又覆盖掉了

**Comment by chenjiandongx** [comment]
@nekolr https://github.com/chenjiandongx/async-proxy-pool/commit/b6869e39ab949700b90b84df58489c41f8d6e3e2 修改好了

**Comment by nekolr** [comment]
好的 谢谢！
