### ISSUE TITLE
看代码不是同时并发多个代理网站

### ISSUE THREAD

**Issue by uxlsl** [chenjiandongx/async-proxy-pool#13]
从总的来看， 是访问一个代理网站，再访问另一个网站

｀｀｀
        for func in all_funcs:
            for proxy in func():
                redis_conn.add_proxy(proxy)
                logger.info("Crawler √ {}".format(proxy）
｀｀｀

**Comment by chenjiandongx** [comment]
这些代理网站都是一个或几个小时才更新一次。并不并发在这里影响不是很大

**Comment by uxlsl** [comment]
嗯嗯！感觉utils.requests 和requests.get 没什么区别

**Comment by chenjiandongx** [comment]
尝鲜

**Comment by uxlsl** [comment]
好的，谢谢！
