### ISSUE TITLE
用https的网站来测试，requests会用本机来调用，似乎并不准确

### ISSUE THREAD

**Issue by znl1087** [chenjiandongx/async-proxy-pool#7]
用test_proxy测试时候发现，用一个https的网址来测试，本机的ip被ban了，好像用requests的proxies的时候，只设置http代理的话，https的访问并不会走代理。
我自己加上了一句话才好用
`proxy['https'] = proxy['http']`

**Comment by chenjiandongx** [comment]
这句是加在哪里？

**Comment by znl1087** [comment]
测试的时候，我建议可以在http接口返回代理的时候，直接把https代理也给设置上。
主要原因还是因为requests调用代理的时候，如果没有设置https代理的话，https的访问就不走代理了，所以我认为你这个测试脚本如果不改动，测试是不准确的。

**Comment by chenjiandongx** [comment]
欢迎提供 PR 改进 :smile:

**Comment by znl1087** [comment]
麻烦看一下PR呀

**Comment by chenjiandongx** [comment]
已经合并 感谢您的贡献！
