### ISSUE TITLE
运行server.py报错

### ISSUE THREAD

**Issue by Juaran** [chenjiandongx/async-proxy-pool#9]
[INFO] Goin' Fast @ http://localhost:3289
[ERROR] Unable to start server

OSError: [Errno 99] error while attempting to bind on address ('::1', 3289, 0, 0): cannot assign requested address

**Comment by chenjiandongx** [comment]
你是什么都没改 然后直接启动就抱这个错？

**Comment by chenjiandongx** [comment]
获取你拉取最新的提交 然后运行
```bash
$ python server_flask.py
```
试试看
